Feature/auth UI
ReavDev/reavpages-app pull request #5
Opened 2024-10-14 05:57 UTC by Vchiazam

Login page UI with validation and error handling
Registration page with form fields for user input
Password recovery page with email input for sending reset links
Mobile responsiveness for all authentication pages
Integration with form handling library (react-hook-form)
Changes Implemented:
Created UI components for login, registration, and password recovery
Added client-side form validation
Applied consistent styling using Tailwind CSS
Integrated with custom input components for form fields
Configured routing for auth-related pages in the app folder

2024-10-16 09:17 UTC, chumex412 requested changes

2024-10-16 09:17 UTC, chumex412 commented on src/modules/auth/index.tsx
> +      <IfElse
Still not feeling this approach.

2024-10-16 09:17 UTC, chumex412 commented on src/modules/auth/forgot-password/index.tsx
> +      <form className="mt-6 space-y-5">
no form validation?

2024-10-16 09:17 UTC, chumex412 commented on src/modules/auth/login/index.tsx
> +      <form className="mt-4 space-y-5">
No form validation here too.

2024-10-16 09:17 UTC, chumex412 commented on src/modules/auth/reset-password/reset-password-form.tsx
> +        <form className="mt-6 space-y-6">
Form validation missing here too.

2024-10-16 09:17 UTC, chumex412 commented on src/modules/auth/sign-up/index.tsx
> +      <form className="mt-6 space-y-5">
Form validation missing here too.

2024-10-16 09:17 UTC, chumex412 commented on tailwind.config.ts
> +     inputText: "#676767", // For input field text
why hardcode the color values? It's preferrable to follow this format for collaborative projects. See the link below:

https://tailwindcss.com/docs/customizing-colors#using-css-variables

2024-10-16 09:36 UTC, Vchiazam commented on .vscode/settings.json
Yh, I have used gitignore

2024-10-16 09:37 UTC, Vchiazam commented on package.json
> +    "dev": "next dev -p 3001",
.....i forgot to remove it, just for my Local pc

2024-10-16 09:38 UTC, Vchiazam commented on src/components/button/index.tsx
> +  {
It's the fall back font... Most of the buttons on the design use jaka font.

2024-10-16 09:39 UTC, Vchiazam commented on src/components/button/index.tsx
> +          {children}
Yes boss 💪 
Tho it's rare, but it works

2024-10-16 09:41 UTC, Vchiazam commented on src/components/global/ThemeSwitcher.tsx
> +import useGlobal from "@/hooks/global"
Emmm, that's the work of an extension installed by the person that initialized the project.  It auto arranges css classes and import statements

2024-10-16 09:45 UTC, Vchiazam commented on src/components/global/ThemeSwitcher.tsx
>   const teams = [
Will fix this.. but I am not the author. I pulled and saw updates regarding theme and the rest.

2024-10-16 09:45 UTC, Vchiazam commented on src/components/input/file-upload.tsx
> +  value: any
Noted boss

2024-10-16 09:46 UTC, Vchiazam commented on src/components/menu/TabSwitcher.tsx
> +  w,
That's an oversight 😟

2024-10-16 09:47 UTC, Vchiazam commented on src/fonts/index.ts
>  })
The design has many fonts tho.

2024-10-16 09:49 UTC, Vchiazam commented on src/modules/auth/forgot-password/index.tsx
> +      <form className="mt-6 space-y-5">
I haven't done form validation, boss shalom said I should fix the UI before UX in terms of validation when clickingor typing and the rest. So that will be in my next PR boss 😁

2024-10-18 09:08 UTC, chumex412 commented on src/components/button/index.tsx
> +  {
pass it in the global.scss

2024-10-20 21:50 UTC, Vchiazam commented on src/components/if-else/index.tsx
The component approach is used to keep the conditional rendering logic within JSX so that the logic feels declarative and flows naturally with the React render flow.

2024-10-21 07:40 UTC, chumex412 commented on package.json
> +    "dev": "next dev -p 3001",
still here

2024-10-23 08:50 UTC, merged